package tests

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/HORNET-Storage/Scionic-Merkle-Tree/v2/dag"
)

// The spec-vector corpus is the cross-language parity fixture: DAGs, partials,
// transmission packets, batched packets and deliberately broken DAGs generated by
// `go run ./tools/specvectors` and committed into all three repos. Go, Swift and
// Rust each run these same seven assertions against their own committed copy.
//
// Go generates the corpus, so on its own this file is close to a self-check. Its
// value is that the other two ports run the SAME seven assertions: when a port
// disagrees, this file establishes what the correct answer was.
//
// A missing corpus is a hard failure here, never a skip. The Swift port skipped
// when its corpus was absent -- which it always was, because it resolved to a
// sibling checkout that nobody had -- and reported green for four releases while
// checking nothing.

type specNegativeVector struct {
	Path        string `json:"path"`
	Kind        string `json:"kind"`
	Description string `json:"description"`
}

type specVectorCase struct {
	Name                string               `json:"name"`
	RootKind            string               `json:"root_kind"`
	RootInputPath       string               `json:"root_input_path"`
	RootHash            string               `json:"root_hash"`
	LeafCount           int                  `json:"leaf_count"`
	FileLeaves          int                  `json:"file_leaves"`
	DirectoryLeaves     int                  `json:"directory_leaves"`
	ChunkLeaves         int                  `json:"chunk_leaves"`
	FullDag             string               `json:"full_dag"`
	PartialDags         []string             `json:"partial_dags"`
	TransmissionPackets []string             `json:"transmission_packets"`
	BatchedPackets      []string             `json:"batched_packets"`
	NegativeVectors     []specNegativeVector `json:"negative_vectors"`
}

type specVectorManifest struct {
	ChunkSize int              `json:"chunk_size"`
	BatchSize int              `json:"batch_size"`
	Cases     []specVectorCase `json:"cases"`
}

// specVectorsRoot is relative to this package directory, which is the working
// directory `go test` uses.
const specVectorsRoot = "../spec/vectors"

func loadSpecVectorManifest(t *testing.T) specVectorManifest {
	t.Helper()

	path := filepath.Join(specVectorsRoot, "manifest.json")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("spec-vector corpus missing at %s: %v\nRegenerate it with: go run ./tools/specvectors -out spec/vectors", path, err)
	}

	var manifest specVectorManifest
	if err := json.Unmarshal(data, &manifest); err != nil {
		t.Fatalf("could not decode %s: %v", path, err)
	}
	if len(manifest.Cases) == 0 {
		t.Fatal("spec-vector manifest lists no cases; every assertion below would pass vacuously")
	}
	return manifest
}

func specVectorPath(relative string) string {
	return filepath.Join(specVectorsRoot, filepath.FromSlash(relative))
}

func readSpecVectorFile(t *testing.T, relative string) []byte {
	t.Helper()
	data, err := os.ReadFile(specVectorPath(relative))
	if err != nil {
		t.Fatalf("could not read spec vector %s: %v", relative, err)
	}
	return data
}

func countLeafTypes(d *dag.Dag) (files, directories, chunks int) {
	for _, leaf := range d.Leafs {
		switch leaf.Type {
		case dag.FileLeafType:
			files++
		case dag.DirectoryLeafType:
			directories++
		case dag.ChunkLeafType:
			chunks++
		}
	}
	return files, directories, chunks
}

func assertShapeMatches(t *testing.T, label string, d *dag.Dag, expected specVectorCase) {
	t.Helper()
	if d.Root != expected.RootHash {
		t.Errorf("%s: root = %s, want %s", label, d.Root, expected.RootHash)
	}
	if len(d.Leafs) != expected.LeafCount {
		t.Errorf("%s: leaf count = %d, want %d", label, len(d.Leafs), expected.LeafCount)
	}
	files, directories, chunks := countLeafTypes(d)
	if files != expected.FileLeaves || directories != expected.DirectoryLeaves || chunks != expected.ChunkLeaves {
		t.Errorf("%s: leaf types = %d file / %d directory / %d chunk, want %d / %d / %d",
			label, files, directories, chunks,
			expected.FileLeaves, expected.DirectoryLeaves, expected.ChunkLeaves)
	}
}

func TestSpecVectorFullDagsParseAndVerify(t *testing.T) {
	for _, vectorCase := range loadSpecVectorManifest(t).Cases {
		d, err := dag.ReadDag(specVectorPath(vectorCase.FullDag))
		if err != nil {
			t.Fatalf("%s: could not read full DAG: %v", vectorCase.Name, err)
		}
		assertShapeMatches(t, vectorCase.Name, d, vectorCase)
		if err := d.Verify(); err != nil {
			t.Errorf("%s: full DAG does not verify: %v", vectorCase.Name, err)
		}
	}
}

// TestSpecVectorFullDagCBORIsDeterministic requires that encoding the same DAG
// twice produces the same bytes.
//
// This is not a theoretical property. Go's default CBOR encoder sorts nothing, so
// a Go map -- Leafs, Proofs, Relationships -- encodes in Go's deliberately
// randomized iteration order, and generating this corpus three times produced
// three different dag.cbor files for identical input. Nothing was corrupted, since
// a CID is computed from leaf fields rather than from this envelope and CBOR maps
// are unordered to any decoder. But it made the serialized form unusable as an
// identity: you cannot digest it, cache by it, dedupe on it, or diff it.
//
// The same trap exists in any port whose hash-map iteration order is not stable,
// which is why this assertion is one of the seven rather than a Go-only test.
func TestSpecVectorFullDagCBORIsDeterministic(t *testing.T) {
	for _, vectorCase := range loadSpecVectorManifest(t).Cases {
		d, err := dag.FromCBOR(readSpecVectorFile(t, vectorCase.FullDag))
		if err != nil {
			t.Fatalf("%s: could not decode full DAG: %v", vectorCase.Name, err)
		}

		first, err := d.ToCBOR()
		if err != nil {
			t.Fatalf("%s: could not encode full DAG: %v", vectorCase.Name, err)
		}
		second, err := d.ToCBOR()
		if err != nil {
			t.Fatalf("%s: could not re-encode full DAG: %v", vectorCase.Name, err)
		}
		if !bytes.Equal(first, second) {
			t.Errorf("%s: encoding the same DAG twice produced different bytes", vectorCase.Name)
		}

		roundTripped, err := dag.FromCBOR(first)
		if err != nil {
			t.Fatalf("%s: could not decode re-encoded DAG: %v", vectorCase.Name, err)
		}
		assertShapeMatches(t, vectorCase.Name+" (round trip)", roundTripped, vectorCase)
		if err := roundTripped.Verify(); err != nil {
			t.Errorf("%s: round-tripped DAG does not verify: %v", vectorCase.Name, err)
		}
	}
}

// TestSpecVectorInputRootsRebuildIdentically is the only test here that exercises
// DAG construction rather than decoding: it rebuilds each DAG from the committed
// input tree and requires the same root CID. This is what makes the corpus a spec
// rather than a snapshot -- a port can only pass by chunking, naming, sorting and
// hashing exactly the way the reference does.
func TestSpecVectorInputRootsRebuildIdentically(t *testing.T) {
	manifest := loadSpecVectorManifest(t)

	dag.SetChunkSize(manifest.ChunkSize)
	defer dag.SetDefaultChunkSize()

	for _, vectorCase := range manifest.Cases {
		inputPath := specVectorPath("cases/" + vectorCase.Name + "/" + vectorCase.RootInputPath)
		rebuilt, err := dag.CreateDag(inputPath, false)
		if err != nil {
			t.Fatalf("%s: could not rebuild DAG from committed input: %v", vectorCase.Name, err)
		}
		assertShapeMatches(t, vectorCase.Name+" (rebuilt)", rebuilt, vectorCase)
		if err := rebuilt.Verify(); err != nil {
			t.Errorf("%s: rebuilt DAG does not verify: %v", vectorCase.Name, err)
		}
	}
}

func TestSpecVectorPartialDagsParseAndVerify(t *testing.T) {
	checked := 0
	genuinelyPartial := 0
	for _, vectorCase := range loadSpecVectorManifest(t).Cases {
		for _, partialPath := range vectorCase.PartialDags {
			partial, err := dag.ReadDag(specVectorPath(partialPath))
			if err != nil {
				t.Fatalf("%s: could not read partial %s: %v", vectorCase.Name, partialPath, err)
			}
			if partial.Root != vectorCase.RootHash {
				t.Errorf("%s: partial %s root = %s, want %s", vectorCase.Name, partialPath, partial.Root, vectorCase.RootHash)
			}
			if err := partial.Verify(); err != nil {
				t.Errorf("%s: partial %s does not verify: %v", vectorCase.Name, partialPath, err)
			}
			checked++
			if partial.IsPartial() {
				genuinelyPartial++
			}
		}
	}
	if checked == 0 {
		t.Fatal("no partial vectors in the corpus")
	}
	// Not every partial vector is partial: single_small_file holds exactly one
	// file, so requesting it returns the whole DAG, and GetPartial is right to
	// hand back something that reports IsPartial() == false. Requiring it per
	// vector was wrong. What must hold is that SOME vector takes the
	// proof-carrying path -- otherwise this test would be re-testing full-DAG
	// verification under a different name.
	if genuinelyPartial == 0 {
		t.Fatal("no vector in the corpus verifies through the partial-DAG proof path")
	}
}

// TestSpecVectorNegativeVectorsAreRejected pins the half of the contract the
// positive vectors cannot: a port that accepted everything would pass every other
// test in this file.
//
// The assertion is deliberately "decode or verify must fail", not "the error
// message contains X". Each port has its own error vocabulary, and requiring a
// shared substring would assert that three independent enums agree on wording --
// a requirement no user has, and one that could be satisfied by editing a string.
func TestSpecVectorNegativeVectorsAreRejected(t *testing.T) {
	checked := 0
	for _, vectorCase := range loadSpecVectorManifest(t).Cases {
		for _, negative := range vectorCase.NegativeVectors {
			broken, err := dag.FromCBOR(readSpecVectorFile(t, negative.Path))
			if err == nil {
				if err := broken.Verify(); err == nil {
					t.Errorf("%s: negative vector %q was accepted (%s)", vectorCase.Name, negative.Kind, negative.Description)
				}
			}
			checked++
		}
	}
	if checked == 0 {
		t.Fatal("no negative vectors in the corpus; the positive vectors alone cannot show anything is rejected")
	}
}

func TestSpecVectorTransmissionPacketsReplay(t *testing.T) {
	for _, vectorCase := range loadSpecVectorManifest(t).Cases {
		receiver := &dag.Dag{Root: vectorCase.RootHash, Leafs: make(map[string]*dag.DagLeaf)}

		for _, packetPath := range vectorCase.TransmissionPackets {
			packet, err := dag.TransmissionPacketFromCBOR(readSpecVectorFile(t, packetPath))
			if err != nil {
				t.Fatalf("%s: could not decode %s: %v", vectorCase.Name, packetPath, err)
			}

			first, err := packet.ToCBOR()
			if err != nil {
				t.Fatalf("%s: could not encode %s: %v", vectorCase.Name, packetPath, err)
			}
			second, err := packet.ToCBOR()
			if err != nil {
				t.Fatalf("%s: could not re-encode %s: %v", vectorCase.Name, packetPath, err)
			}
			if !bytes.Equal(first, second) {
				t.Errorf("%s: encoding %s twice produced different bytes", vectorCase.Name, packetPath)
			}

			roundTripped, err := dag.TransmissionPacketFromCBOR(first)
			if err != nil {
				t.Fatalf("%s: could not decode re-encoded %s: %v", vectorCase.Name, packetPath, err)
			}
			if err := receiver.ApplyAndVerifyTransmissionPacket(roundTripped); err != nil {
				t.Fatalf("%s: could not apply %s: %v", vectorCase.Name, packetPath, err)
			}
		}

		assertShapeMatches(t, vectorCase.Name+" (replayed)", receiver, vectorCase)
		if err := receiver.Verify(); err != nil {
			t.Errorf("%s: replayed DAG does not verify: %v", vectorCase.Name, err)
		}
	}
}

func TestSpecVectorBatchedPacketsReplay(t *testing.T) {
	splitCases := 0
	for _, vectorCase := range loadSpecVectorManifest(t).Cases {
		if len(vectorCase.BatchedPackets) > 1 {
			splitCases++
		}
		receiver := &dag.Dag{Root: vectorCase.RootHash, Leafs: make(map[string]*dag.DagLeaf)}

		for _, batchPath := range vectorCase.BatchedPackets {
			batch, err := dag.BatchedTransmissionPacketFromCBOR(readSpecVectorFile(t, batchPath))
			if err != nil {
				t.Fatalf("%s: could not decode %s: %v", vectorCase.Name, batchPath, err)
			}

			first, err := batch.ToCBOR()
			if err != nil {
				t.Fatalf("%s: could not encode %s: %v", vectorCase.Name, batchPath, err)
			}
			second, err := batch.ToCBOR()
			if err != nil {
				t.Fatalf("%s: could not re-encode %s: %v", vectorCase.Name, batchPath, err)
			}
			if !bytes.Equal(first, second) {
				t.Errorf("%s: encoding %s twice produced different bytes", vectorCase.Name, batchPath)
			}

			roundTripped, err := dag.BatchedTransmissionPacketFromCBOR(first)
			if err != nil {
				t.Fatalf("%s: could not decode re-encoded %s: %v", vectorCase.Name, batchPath, err)
			}
			if err := receiver.ApplyAndVerifyBatchedTransmissionPacket(roundTripped); err != nil {
				t.Fatalf("%s: could not apply %s: %v", vectorCase.Name, batchPath, err)
			}
		}

		assertShapeMatches(t, vectorCase.Name+" (batch replayed)", receiver, vectorCase)
		if err := receiver.Verify(); err != nil {
			t.Errorf("%s: batch-replayed DAG does not verify: %v", vectorCase.Name, err)
		}
	}

	// Without this, a corpus that happened to fit every case in one batch would
	// still pass -- and the batch-splitting path, which is where the interesting
	// proof bugs live, would go untested while looking tested.
	if splitCases == 0 {
		t.Fatal("no case in the corpus splits across multiple batches; the batching path is untested")
	}
}
