// Command geargen writes dag/fastcdc_gear.go: the frozen fastcdc-v1 gear table.
//
// The table is NORMATIVE and versioned as part of the fastcdc-v1 chunking spec
// (docs/fastcdc-v1.md). It is generated ONCE from a fixed, documented seed and
// checked into the repository as source; every port (Swift, Rust, ...) copies
// the same constants or re-derives them from the same procedure. Any change to
// the seed, the derivation, or a single entry is a NEW chunking version tag,
// never a mutation of fastcdc-v1 — trees only dedup against each other when
// every producer cuts identical boundaries.
//
// Derivation, frozen:
//
//	G[i] = u64be( SHA-256( ASCII "scionic-fastcdc-v1:gear:" ++ byte(i) )[0:8] )
//
// where byte(i) is the single raw byte with value i (0..255), appended after
// the ASCII prefix, and u64be reads the first 8 digest bytes big-endian.
//
// Run from the repository root (the directory containing go.mod):
//
//	go run ./tools/geargen
//
// The dag package's regeneration test re-derives the table independently and
// fails on any drift, so a stale or hand-edited fastcdc_gear.go cannot land.
package main

import (
	"crypto/sha256"
	"encoding/binary"
	"fmt"
	"os"
	"strings"
)

const (
	gearSeedPrefix = "scionic-fastcdc-v1:gear:"
	outputPath     = "dag/fastcdc_gear.go"
)

func main() {
	var out strings.Builder
	out.WriteString("// Code generated by tools/geargen. DO NOT EDIT.\n")
	out.WriteString("//\n")
	out.WriteString("// fastcdc-v1 gear table (NORMATIVE — see docs/fastcdc-v1.md):\n")
	out.WriteString("//\n")
	out.WriteString("//\tG[i] = u64be(SHA-256(\"scionic-fastcdc-v1:gear:\" ++ byte(i))[0:8])\n")
	out.WriteString("//\n")
	out.WriteString("// Regenerate with: go run ./tools/geargen (from the repository root).\n")
	out.WriteString("// TestFastCDCGearTableMatchesSeedDerivation re-derives every entry and\n")
	out.WriteString("// fails on any drift.\n")
	out.WriteString("package dag\n")
	out.WriteString("\n")
	out.WriteString("var fastCDCGear = [256]uint64{\n")
	for i := 0; i < 256; i++ {
		if i%4 == 0 {
			out.WriteString("\t")
		}
		message := append([]byte(gearSeedPrefix), byte(i))
		digest := sha256.Sum256(message)
		value := binary.BigEndian.Uint64(digest[:8])
		fmt.Fprintf(&out, "0x%016x,", value)
		if i%4 == 3 {
			out.WriteString("\n")
		} else {
			out.WriteString(" ")
		}
	}
	out.WriteString("}\n")

	if err := os.WriteFile(outputPath, []byte(out.String()), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "geargen: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s (256 entries)\n", outputPath)
}
