name: Test & Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version: 1.24.0

    - name: Build
      run: go build -v ./...

    - name: Test (with cross-package coverage)
      run: |
        go test ./... \
          -v \
          -race \
          -covermode=atomic \
          -coverpkg=./... \
          -coverprofile=coverage.txt

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
